quarkus.application.name=notification-service
quarkus.http.port=8080
quarkus.http.auth.form.enabled=false
quarkus.http.auth.basic=false

smallrye.jwt.path.groups=role
quarkus.oidc.token.signature-algorithm=rs256
quarkus.oidc.application-type=service
quarkus.messaging.kafka.serializer-generation.enabled=true
quarkus.native.resources.includes=*.properties

kafka.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
kafka.group.id=notification-service-${HOSTNAME}

mp.messaging.connector.smallrye-kafka.auto.offset.reset=latest

mp.messaging.incoming.content-channel.connector=smallrye-kafka
mp.messaging.incoming.content-channel.topics=blog.content.notification
mp.messaging.incoming.content-channel.partitions=1

mp.messaging.incoming.post-like-channel.connector=smallrye-kafka
mp.messaging.incoming.post-like-channel.topics=blog.like.post
mp.messaging.incoming.post-like-channel.partitions=1

mp.messaging.incoming.comment-like-channel.connector=smallrye-kafka
mp.messaging.incoming.comment-like-channel.topics=blog.like.comment
mp.messaging.incoming.comment-like-channel.partitions=1

mp.messaging.incoming.post-view-channel.connector=smallrye-kafka
mp.messaging.incoming.post-view-channel.topics=blog.post.view.aggregation
mp.messaging.incoming.post-view-channel.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
mp.messaging.incoming.post-view-channel.partitions=1

mp.messaging.outgoing.activity-notification.connector=smallrye-kafka
mp.messaging.outgoing.activity-notification.topics=blog.activity
mp.messaging.outgoing.activity-notification.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.activity-notification.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

quarkus.native.container-build=true
quarkus.native.container-runtime=docker
quarkus.container-image.build=true
quarkus.container-image.group=blog
quarkus.container-image.name=${quarkus.application.name}
quarkus.container-image.tag=v1
quarkus.container-image.image=ghcr.io/Ambrosia0/${quarkus.application.name}
quarkus.container-image.push=false
# quarkus.container-image.registry=localhost:5000
quarkus.jib.base-native-image=quay.io/quarkus/quarkus-distroless-image:2.0


quarkus.kubernetes.deploy=false
quarkus.kubernetes.image-pull-policy=never
quarkus.kubernetes.deployment-kind=deployment
quarkus.kubernetes.service-account=default
quarkus.kubernetes.namespace=blog
quarkus.kubernetes.replicas=1
quarkus.kubernetes.env.vars.HOSTNAME=metadata.name
quarkus.kubernetes.ports.http.container-port=8080
quarkus.kubernetes.ports.http.host-port=80
quarkus.kubernetes.service-type=ClusterIP
quarus.kubernetes.env.configmaps=oidc-config

# in dev cluster
# quarkus.oidc.token.issuer=any
quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=${OIDC_ISSUER_URL:unset}
mp.messaging.connector.smallrye-kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

%prod.quarkus.oidc.auth-server-url=${OIDC_ISSUER_URL}
%prod.mp.messaging.connector.smallrye-kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}