javaVersion=25
springBootVersion=4.1.0
springCloudVersion=2025.1.2
jacksonCoreVersion=2.21.0
googleProtobufPlugin=0.10.0
grpcCodeGen=1.80.0
springDependencyManagement=1.1.7
springGrpc=1.0.3
postgresqlJDBC=42.7.7
postgresqlR2DBC=1.0.7.RELEASE
nimbus=10.3.1
testContainers=2.0.3
testContainersKeycloak=3.4.0
testContainersKafka=1.21.4
liquibase=5.0.1
springdoc=2.8.14
lingua=1.2.2
org.gradle.caching=true
org.gradle.configuration-cache=true
resilience4j=2.4.0
awsS3=4.1.0
graalVmPluginVer=0.11.5
uuidv7Lib=1.1.0
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m