FROM postgres:18 AS builder

RUN apt-get update && apt-get install -y \
    git build-essential postgresql-server-dev-18

RUN git clone https://github.com/postgrespro/rum /rum \
 && cd /rum \
 && make USE_PGXS=1 \
 && make USE_PGXS=1 install DESTDIR=/out

FROM postgres:18

COPY --from=builder /out/usr /usr

RUN ldconfig