apiVersion: v1
kind: Service
metadata:
  name: communitydb
  namespace: blog
spec:
  selector:
    app: community-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service-postgres
  labels:
    app: community-service-postgres
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-service-postgres
  template:
    metadata:
      labels:
        app: community-service-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:18
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: community-db
                key: username
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: community-db
                key: url
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: community-db
                key: password