apiVersion: v1
kind: Service
metadata:
  name: contentdb
  namespace: blog
spec:
  selector:
    app: content-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service-postgres
  labels:
    app: content-service-postgres
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service-postgres
  template:
    metadata:
      labels:
        app: content-service-postgres
    spec:
      containers:
      - name: postgres
        image: ghcr.io/ambrosia0/postgres-18-rum
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: content-db
                key: username
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: content-db
                key: url
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: content-db
                key: password
      #   volumeMounts:
      #     - name: file-service-storage
      #       mountPath: /var/lib/postgresql/data/
      # volumes:
      # - name: file-service-storage
      #   persistentVolumeClaim:
      #     claimName: file-service-pvc