apiVersion: v1
kind: Service
metadata:
  name: s3-storage-service
  namespace: blog
spec:
  selector:
    app: s3-storage
  ports:
    - port: 9000
      protocol: TCP
      name: http
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-storage
  labels:
    app: s3-storage
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-storage
  template:
    metadata:
      labels:
        app: s3-storage
    spec:
      containers:
      - name: s3-storage
        image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
        ports:
          - containerPort: 9000
          - containerPort: 9001
        command:
          - server /data --console-address ":9001"
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "1Gi"
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                key: s3-config
                value: root-user
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: s3-config
                value: root-password
        volumeMounts:
          - mountPath: /data
            name: minio-data
      volumes:
        - name: mino-data
          emptyDir: {}
      serviceAccountName: default
      automountServiceAccountToken: true