apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:8.6
        ports:
          - containerPort: 6379
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi"
      serviceAccountName: default
      automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: blog
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP