server:
  port: 8080
  ssl:
    enabled: true
    certificate: "/tls/tls.crt"
    certificate-private-key: "/tls/tls.key"
spring:
 application:
  name: api-gateway
 cloud:
    gateway:
      server:
        webflux:
          trusted-proxies: ".*"
          x-forwarded:
            enabled: true
            proto-enabled: true
            proto-append: true
          routes:
          - id: comment_service
            uri: http://comment-service
            predicates:
            - Path=/api/user/comment/**,/api/admin/comment/**,/api/public/comment/**,/api/public/post/*/comments
          - id: report_service
            uri: http://report-service
            predicates:
            - Path=/api/user/report/**,/api/admin/report/**
          - id: content_service
            uri: http://content-service
            predicates:
            - Path=/api/public/post/**,/api/user/post/**,/api/admin/post/**,/api/me/post/**
          - id: community_service
            uri: http://community-service:8080
            predicates:
            - Path=/api/public/community/**,/api/user/community/**,/api/admin/community/**
          - id: notification_service
            uri: http://notification-service
            predicates:
            - Path=/api/user/notification,/api/public/notification
          - id: chat_service
            uri: http://chat-service
            predicates:
            - Path=/api/user/chat/**,/api/admin/chat/**
          - id: keycloak
            uri: http://keycloak.keycloak.svc.cluster.local:8080
            predicates:
            - Path=/auth/realms/**,/auth/resources/**
            filters:
            - PreserveHostHeader
          - id: s3
            uri: ${S3_ENDPOINT:http://localhost:9000}
            predicates:
            - Path=/files/**
            filters:
            - PreserveHostHeader
          - id: profile_service
            uri: http://profile-service
            predicates:
            - Path=/api/user/**,/api/public/**,/api/admin/**,/api/me/**
          - id: frontend_service
            uri: http://frontend-service
            predicates:
            - Path=/**
---
server:
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile:
      - dev
  cloud:
   gateway:
     server:
       webflux:
         globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
                  - "http://localhost:5173"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                - PATCH
              allowedHeaders: "*"
              allowCredentials: true
         trusted-proxies: ".*"
         x-forwarded:
           enabled: true
           proto-enabled: true
           proto-append: true
         routes:
         - id: comment_service
           uri: http://comment-service:8080
           predicates:
           - Path=/api/user/comment/**,/api/admin/comment/**,/api/public/comment/**,/api/public/post/*/comments
         - id: content_service
           uri: http://content-service:8080
           predicates:
           - Path=/api/public/post/**,/api/user/post/**,/api/admin/post/**,/api/me/post/**
         - id: community_service
           uri: http://community-service:8080
           predicates:
           - Path=/api/public/community/**,/api/user/community/**,/api/admin/community/**
         - id: report_service
           uri: http://report-service:8080
           predicates:
           - Path=/api/user/report/**,/api/admin/report/**
         - id: notification_service
           uri: http://notification-service:8080
           predicates:
           - Path=/api/user/notification,/api/public/notification
         - id: chat_service
           uri: http://chat-service:8080
           predicates:
           - Path=/api/user/chat/**,/api/admin/chat/**
         - id: keycloak
           uri: http://keycloak:8080
           predicates:
           - Path=/auth/realms/**,/auth/resources/**
           filters:
           - PreserveHostHeader
         - id: s3
           uri: ${S3_ENDPOINT}
           predicates:
           - Path=/files/**
           filters:
           - PreserveHostHeader
         - id: profile_service
           uri: http://profile-service:8080
           predicates:
           - Path=/api/user/**,/api/public/**,/api/me/**,/api/admin/**
         - id: frontend_service
           uri: http://frontend-service:3000
           predicates:
           - Path=/**
