server:
  port: 8080
  ssl:
    enabled: true
    certificate: "/tls/tls.crt"
    certificate-private-key: "/tls/tls.key"
spring:
 application:
  name: api-gateway
 cloud:
    gateway:
      server:
        webflux:
          trusted-proxies: ".*"
          x-forwarded:
            enabled: true
            proto-enabled: true
            proto-append: true
          routes:
          - id: comment_service
            uri: http://comment-service:8080
            predicates:
            - Path=/api/v1/comment/**,/api/v1/public/comment/**,/api/v1/public/post/*/comments
          - id: report_service
            uri: http://report-service:8080
            predicates:
            - Path=/api/v1/report/**
          - id: content_service
            uri: http://content-service:8080
            predicates:
            - Path=/api/v1/post/**,/api/v1/me/post/**,/api/v1/public/post/**
          - id: community_service
            uri: http://community-service:8080
            predicates:
            - Path=/api/v1/public/community/**,/api/v1/community/**
          - id: notification_service
            uri: http://notification-service:8080
            predicates:
            - Path=/api/v1/notification,/api/v1/public/notification
          - id: keycloak
            uri: http://keycloak.keycloak.svc.cluster.local:8080
            predicates:
            - Path=/auth/realms/**,/auth/resources/**
            filters:
            - PreserveHostHeader
          - id: s3
            uri: ${S3_ENDPOINT:http://localhost:9000}
            predicates:
            - Path=/files/**
            filters:
            - PreserveHostHeader
          - id: profile_service
            uri: http://profile-service:8080
            predicates:
            - Path=/api/v1/public/**,/api/v1/me/**,/api/v1/profile/**
          - id: collaboration-service
            uri: http://collaboration-service:8080
            predicates:
            - Path=/ws/**
          - id: frontend_service
            uri: http://frontend-service:3000
            predicates:
            - Path=/**
---
server:
  ssl:
    enabled: false
spring:
  config:
    activate:
      on-profile:
      - dev
  cloud:
   gateway:
     server:
       webflux:
         globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
                  - "http://localhost:5173"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                - PATCH
              allowedHeaders: "*"
              allowCredentials: true
         trusted-proxies: ".*"
         x-forwarded:
           enabled: true
           proto-enabled: true
           proto-append: true
         routes:
          - id: comment_service
            uri: http://comment-service:8080
            predicates:
            - Path=/api/v1/comment/**,/api/v1/public/comment/**,/api/v1/public/post/*/comments
          - id: report_service
            uri: http://report-service:8080
            predicates:
            - Path=/api/v1/report/**
          - id: content_service
            uri: http://content-service:8080
            predicates:
            - Path=/api/v1/post/**,/api/v1/me/post/**,/api/v1/public/post/**
          - id: community_service
            uri: http://community-service:8080
            predicates:
            - Path=/api/v1/public/community/**,/api/v1/community/**
          - id: notification_service
            uri: http://notification-service:8080
            predicates:
            - Path=/api/v1/notification,/api/v1/public/notification
          - id: keycloak
            uri: http://keycloak.keycloak.svc.cluster.local:8080
            predicates:
            - Path=/auth/realms/**,/auth/resources/**
            filters:
            - PreserveHostHeader
          - id: s3
            uri: ${S3_ENDPOINT:http://localhost:9000}
            predicates:
            - Path=/files/**
            filters:
            - PreserveHostHeader
          - id: profile_service
            uri: http://profile-service:8080
            predicates:
            - Path=/api/v1/public/**,/api/v1/me/**,/api/v1/profile/**
          - id: collaboration-service
            uri: http://collaboration-service:8080
            predicates:
            - Path=/ws/**
          - id: frontend_service
            uri: http://frontend-service:3000
            predicates:
            - Path=/**
